### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡]

### ISSUE THREAD

**Issue by Temuulen0514** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#12]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**
Recycle hiihed iluu taw tuhtai aldaa dutagdalgui bolno gej bdj bn.

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**
Recycle ruu orohoor aldaand orj duushaa unaj bui met zuraglal uzegdsene MNFCUSTOM-iin baruun tald bairlah cantinaruud dund Teleport hiigeed baina eniig shalgaad yanzlaad ogooch. 

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**
Recycle iin bairshiliig hotiin door bairlah cantinaruud dund awaachwal hotoos garaad hol yawaad baih shaardlagagui ih amar baih bolu gej bdj bn. 

**Нэмэлт мэдээлэл?**
![20220825065946_1](https://user-images.githubusercontent.com/111016768/186538718-2a49594c-1294-47da-a6d6-f1e6a7a098a4.jpg)
![20220825065956_1](https://user-images.githubusercontent.com/111016768/186538727-dd7eab7f-446a-41e6-8cb1-19dbce369901.jpg)

**Comment by WalterLoireMNF** [comment]
Шийдвэрлэсэн 18:00 цагаас орно.

![image](https://user-images.githubusercontent.com/105988287/186581185-2effc8b2-02e0-4847-baed-730ce9411e8a.png)

https://discord.com/channels/752498764865994814/907116563176501288/1012229818361839646
