### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡]

### ISSUE THREAD

**Issue by BAYLSPD** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#3]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**
Цагдаагийн хэлтэс дээр иргэд иргэний үнэмлэхгүй ирсэн учир тухайн иргэнг хэн гэдгийг цаг алдалгүй тодруулах улмаар хэргийг хурдан шийдвэрлэнэ 

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**
Цагдаагийн хэлтэсийн түр саатулах байрны хажуу өрөөнд иргэний бүртгэлийн  материал авч болдог болох хотын захиргааны байр дээрээс иргэний үнэмлэх захиалдаг шиг

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Дараагийн Цунами-аар шийдэгдсэн. Амжилт хүсье. 💯 

https://discord.com/channels/752498764865994814/907116563176501288/1011240701016690813
