### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡] Эмнэлэгт машин нэмэх

### ISSUE THREAD

**Issue by MNFCANDYNETWORK** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#4]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**

Эмчийн дарга-н хүсэлт 

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**

Эмчийн дарга-н хүсэлт

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

Эмчийн дарга-н хүсэлт

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Өмнөх машины хурд нэмж шийдсэн болно.
