### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡] Walking Style хадгалагддаг болгох

### ISSUE THREAD

**Issue by MNFCANDYNETWORK** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#5]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**

Тоглогч-н хүсэлт

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**

Тоглогч-н хүсэлт

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

Тоглогч-н хүсэлт

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Шийдвэрлэсэн. 06:00 цагаас орно.

https://discord.com/channels/752498764865994814/992691410924994640/1012303161253449729
