### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡] MNFCUSTOMS дэлгүүр-г дарга л хэрэглэдэг болгох

### ISSUE THREAD

**Issue by MNFCANDYNETWORK** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#6]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**

Засварын дарга-н хүсэлт

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**

Засварын дарга-н хүсэлт

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

Засварын дарга-н хүсэлт

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Шийдвэрлэсэн. 18:00 цунами-р орно.

https://discord.com/channels/752498764865994814/907116563176501288/1011552857159380992
