### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡] Bennys-н засварт хүмүүс машинаа засхаар ажлын данс руу ордог болгох

### ISSUE THREAD

**Issue by MNFCANDYNETWORK** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#7]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**

Bennys хүсэлт

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**

Bennys хүсэлт

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

Bennys хүсэлт

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Шийдэгдсэн. 18:00 цагаас орно.

https://discord.com/channels/752498764865994814/907116563176501288/1011563125297922141

[Benny] - Хүн засвар ороод хийхэд ажлын данс руу нь хийлгэсэн засварын мөнгө ордог болов.
