### ISSUE TITLE
[💡САНАЛ ХҮСЭЛТ💡] /depot -ийг Log System-тэй болгох

### ISSUE THREAD

**Issue by MNFCANDYNETWORK** [MNFCANDYNETWORK/MNFCANDY-ROLEPLAY#9]
**Таны хүсэж буй өөрчлөлт ямар давуу тал авчрах вэ?**

Тоглогч-н хүсэлт

**Таны өөрчлөлт манай талаас ямар зүйлс дээр засвар хийх шаардлагатай вэ?**

Тоглогч-н хүсэлт

**Хэрэв таны эхний хүсэлт боломжгүй бол өөр ямар байдлаар таны санааг хэрэгжүүлэх боломжтой вэ?**

Тоглогч-н хүсэлт

**Нэмэлт мэдээлэл?**

**Comment by WalterLoireMNF** [comment]
Хэрэгжүүлсэн. 18:00 цаг цунами-р орно.

https://discord.com/channels/752498764865994814/907116563176501288/1011547860547944469
